# Generated by Django 2.1.2 on 2018-10-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('hid', models.CharField(max_length=32)),
                ('rid', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=10)),
                ('community_name', models.CharField(max_length=256)),
                ('area_name', models.CharField(max_length=256)),
                ('price_total', models.BigIntegerField(verbose_name=10)),
                ('price_total_unit', models.CharField(max_length=10)),
                ('unit_price', models.BigIntegerField(verbose_name=10)),
                ('transaction', models.TextField()),
                ('cost_payment', models.TextField()),
                ('input_time', models.TimeField()),
            ],
        ),
    ]
