# Generated by Django 2.1.2 on 2018-10-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='input_time',
            field=models.DateTimeField(),
        ),
    ]
