# Generated by Django 2.1.2 on 2018-10-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20181022_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='area_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='community_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='cost_payment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='hid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='input_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='origin_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='price_total',
            field=models.BigIntegerField(null=True, verbose_name=10),
        ),
        migrations.AlterField(
            model_name='estate',
            name='price_total_unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='rid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='transaction',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='unit_price',
            field=models.BigIntegerField(null=True, verbose_name=10),
        ),
    ]
